blog/urls.py
# Third party imports.
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)

# Local application imports.
from . import views

# Specifies the app's name.
app_name = "blog"

urlpatterns = [
    path('', PostListView.as_view(), name='home'),  # url for post list.
    path('user/<str:username>/',
         UserPostListView.as_view(),
         name='user-posts'),  # url for specific user post.
    path('post/<int:pk>/',
         PostDetailView.as_view(),
         name='post-detail'),  # url for post detail.
    path('post/new/',
         PostCreateView.as_view(),
         name='post-create'),  # url to create new post.
    path('post/<int:pk>/update/',
         PostUpdateView.as_view(),
         name='post-update'),  # url to update post.
    path('post/<int:pk>/delete/',
         PostDeleteView.as_view(), name='post-delete'),  # url to delete post.
]

blog_config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),  # Urls for the admin app.
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'),  # Url for login.
    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'),  # Url for logout.
    path('', include('blog.urls', namespace='blog')),  # Urls for the blog app.
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# Third party imports.
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

def user_directory_path(instance, filename):
    return 'uploads/user_{0}/{1}'.format(instance.title, filename)
class Post(models.Model):
    title = models.CharField(max_length=30, default='')
    summary = models.CharField(max_length=60, default='')
    body = models.CharField(max_length=300, default='')
    date_posted = models.DateTimeField(default=timezone.now)
    document = models.FileField(default='placeholder.pdf', upload_to=user_directory_path)
    tags = models.CharField(default='', max_length=300, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.pk})
    
    def save(self, **kwargs):
        super().save()

users/models.py
# Standard Library imports

# Third Party imports
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import RegexValidator
from django import forms


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10, validators=[RegexValidator(
        regex='^[0-9]{10}$')], default='123456789')
    name = models.CharField(max_length=50, default='FirstName LastName')
    pincode = models.CharField(max_length=6, 
        validators=[RegexValidator(regex='^[0-9]{6}$')], default='123456')
    # Optional Fields
    address = models.CharField(max_length=50, blank=True, default='')
    city = models.CharField(max_length=50, blank=True, default='')
    state = models.CharField(max_length=50, blank=True, default='')
    country = models.CharField(max_length=50, blank=True, default='')

    def __str__(self):
        return f"{self.user.username}'s Profile"

    def save(self, **kwargs):
        super().save()

blog/forms.py
# Third party imports
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Local application import
from .models import Post

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['document']

users/forms.py
# Third party imports
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Local application import
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'phone', 'pincode', 'city', 'address', 'state', 'country']

blog/views.py
# Third party  imports.
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

# Local application import
from .models import Post
from .forms import PostUpdateForm


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'summary', 'body', 'document']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'summary', 'body', 'document']

    def form_valid(self, form):
        # self.post.save(self.document.name, self.document, save=False)
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created!\
                            You are now able to log in')
            return redirect('profile')
    else:
        form = UserRegisterForm()
    
    context = {'form': form}
    template_name = 'users/register.html'
    
    return render(request, template_name, context)


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    template_name = 'users/profile.html'

    return render(request, template_name, context)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

  <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
  <title>Blog</title>
</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'blog:home' %}"> {{ user.profile.name }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'blog:post-create' %}">New Post
            </a>
            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile
            </a>
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">Register
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-12">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </main>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js">

    </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js">

    </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>

</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2"
                 href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}
              </a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}
              </small>
            </div>
            <h2><a class="article-title"
                   href="{% url 'blog:post-detail' post.id %}">{{ post.title }}
                </a>
            </h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}

    {# Pagination for blog post #}
    {% if is_paginated %}

        {# Displays previous pages #}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4"
               href="?page={{ page_obj.previous_page_number }}">Previous
            </a>
        {% endif %}

        {# Displays current page #}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
         {% endfor %}

        {# Displays next pages #}
       {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4"
               href="?page={{ page_obj.next_page_number }}">Next
            </a>
            <a class="btn btn-outline-info mb-4"
               href="?page={{ page_obj.paginator.num_pages }}">Last
            </a>
        {% endif %}

    {% endif %}
{% endblock content %}

blog/templates/blog/post_cofirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"
                </h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete
                </button>
                <a class="btn btn-outline-secondary"
                   href="{% url 'blog:post-detail' object.id %}">Cancel
                </a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
 {% extends "blog/base.html" %} 
 {% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the post "{{ object.title }}"
            </h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete
            </button>
            <a class="btn btn-outline-secondary"
               href="{% url 'blog:post-detail' object.id %}">Cancel
            </a>
        </div>
    </form>
</div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'blog:user-posts' object.author.username %}">{{ object.author }}
      </a>
      <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
      {% if object.author == user %}
      <div>
        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post-update' object.id %}">Update
        </a>
        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' object.id %}">Delete
        </a>
      </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ object.title }}</h2>
    <p class="article-content">{{ object.summary }}</p>
    <hr>
    <p class="article-content">{{ object.body }}</p>
    <a href="../../media/{{ object.document }}">{{ object.document }}</a>
  </div>
</article>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})
    </h1>
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2"
                 href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}
              </a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title"
                   href="{% url 'blog:post-detail' post.id %}">{{ post.title }}
                </a>
            </h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}

    {# Pagination for blog post #}
    {% if is_paginated %}

        {# Displays previous pages #}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4"
               href="?page={{ page_obj.previous_page_number }}">Previous
            </a>
        {% endif %}

        {# Displays current page #}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
         {% endfor %}

        {# Displays next pages #}
       {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4"
               href="?page={{ page_obj.next_page_number }}">Next
            </a>
            <a class="btn btn-outline-info mb-4"
               href="?page={{ page_obj.paginator.num_pages }}">Last
            </a>
        {% endif %}

    {% endif %}
{% endblock content %}

users/templates/users/login.html
{% extends "blog/base.html" %} 
{% load crispy_forms_tags %} 
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
                Need An Account? <a class="ml-2"
                                    href="{% url 'register' %}">Sign Up Now
                                </a>
        </small>
    </div>
</div>
{% endblock content %}

users/templates/users/logout.html
 {% extends "blog/base.html" %} 
 {% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3">
    <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
</div>
{% endblock content %}

users/templates/users/profile.html
 {% extends "blog/base.html" %} 
 {% load crispy_forms_tags %}
  {% block content %}
<div class="content-section">
    <div class="media">
        <div class="media-body">
            <h2 class="account-heading">{{ user.profile.name }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ u_form|crispy }} 
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/register.html
 {% extends "blog/base.html" %} 
 {% load crispy_forms_tags %} 
 {% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
                Already Have An Account? <a class="ml-2"
                                            href="{% url 'login' %}">Sign In
                                         </a>
        </small>
    </div>
</div>
{% endblock content %}